/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AtletaControl;
import exception.CampoVazioException;
import exception.NumeroInvalidoException;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class FrmPanel extends javax.swing.JFrame {

    /**
     * Creates new form FrmPanel
     */
    
    AtletaControl atleta;
    public FrmPanel() {
        initComponents();
        atleta = new AtletaControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        btnCad = new javax.swing.JButton();
        btnMediaPeso = new javax.swing.JButton();
        btnMaisAlto = new javax.swing.JButton();
        btnMaiorMenorIdade = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        txtNomeBusca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblNomeBusca = new javax.swing.JLabel();
        lblNPesoBusca = new javax.swing.JLabel();
        lblAlturaBusca = new javax.swing.JLabel();
        lblIdadeBusca = new javax.swing.JLabel();
        txtPesoBusca = new javax.swing.JTextField();
        txtAlturaBusca = new javax.swing.JTextField();
        txtIdadeBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBuscaNome = new javax.swing.JButton();
        btnBuscaPeso = new javax.swing.JButton();
        btnBuscaAltura = new javax.swing.JButton();
        btnBuscaIdade = new javax.swing.JButton();
        btnExcluirNome = new javax.swing.JButton();
        btnExcluirPeso = new javax.swing.JButton();
        btnExcluirAltura = new javax.swing.JButton();
        btnExcluirIdade = new javax.swing.JButton();
        btnExcluirEspec = new javax.swing.JButton();
        lblCodigoBusca = new javax.swing.JLabel();
        txtCodigoBusca = new javax.swing.JTextField();
        btnBuscaCodigo = new javax.swing.JButton();
        btnExcluirCodigo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome");

        lblPeso.setText("Peso");

        lblAltura.setText("Altura");

        lblIdade.setText("Idade");

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnMediaPeso.setText("Média dos pesos");
        btnMediaPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaPesoActionPerformed(evt);
            }
        });

        btnMaisAlto.setText("Atleta mais alto");
        btnMaisAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisAltoActionPerformed(evt);
            }
        });

        btnMaiorMenorIdade.setText("Maiores e menores de Idade");
        btnMaiorMenorIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaiorMenorIdadeActionPerformed(evt);
            }
        });

        btnListar.setText("Listar atletas cadastrados");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar atletas");

        lblNomeBusca.setText("Nome");

        lblNPesoBusca.setText("Peso");

        lblAlturaBusca.setText("Altura");

        lblIdadeBusca.setText("Idade");

        txtPesoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoBuscaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar Geral");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscaNome.setText("Buscar");
        btnBuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaNomeActionPerformed(evt);
            }
        });

        btnBuscaPeso.setText("Buscar");
        btnBuscaPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaPesoActionPerformed(evt);
            }
        });

        btnBuscaAltura.setText("Buscar");
        btnBuscaAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaAlturaActionPerformed(evt);
            }
        });

        btnBuscaIdade.setText("Buscar");
        btnBuscaIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaIdadeActionPerformed(evt);
            }
        });

        btnExcluirNome.setText("Excluir");
        btnExcluirNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirNomeActionPerformed(evt);
            }
        });

        btnExcluirPeso.setText("Excluir");
        btnExcluirPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPesoActionPerformed(evt);
            }
        });

        btnExcluirAltura.setText("Excluir");
        btnExcluirAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAlturaActionPerformed(evt);
            }
        });

        btnExcluirIdade.setText("Excluir");
        btnExcluirIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirIdadeActionPerformed(evt);
            }
        });

        btnExcluirEspec.setText("Excluir Especificado");
        btnExcluirEspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEspecActionPerformed(evt);
            }
        });

        lblCodigoBusca.setText("Codigo");

        btnBuscaCodigo.setText("Buscar");
        btnBuscaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCodigoActionPerformed(evt);
            }
        });

        btnExcluirCodigo.setText("Excluir");
        btnExcluirCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMediaPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMaisAlto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMaiorMenorIdade))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblIdade)
                            .addGap(18, 18, 18)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAltura)
                                .addComponent(lblPeso)
                                .addComponent(lblNome))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(txtPeso)
                                .addComponent(txtAltura))))
                    .addComponent(jLabel1)
                    .addComponent(btnCad)
                    .addComponent(btnListar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNPesoBusca)
                                    .addComponent(lblNomeBusca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPesoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIdadeBusca)
                                .addGap(20, 20, 20)
                                .addComponent(txtIdadeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAlturaBusca)
                                .addGap(18, 18, 18)
                                .addComponent(txtAlturaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodigoBusca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscaNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscar)
                                    .addComponent(btnBuscaIdade)
                                    .addComponent(btnBuscaAltura)
                                    .addComponent(btnBuscaPeso)
                                    .addComponent(btnBuscaCodigo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcluirCodigo)
                                    .addComponent(btnExcluirNome)
                                    .addComponent(btnExcluirPeso)
                                    .addComponent(btnExcluirAltura)
                                    .addComponent(btnExcluirIdade)
                                    .addComponent(btnExcluirEspec))))))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCad)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMediaPeso)
                    .addComponent(btnMaisAlto)
                    .addComponent(btnMaiorMenorIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListar)
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoBusca)
                    .addComponent(txtCodigoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCodigo)
                    .addComponent(btnExcluirCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirNome)
                    .addComponent(btnBuscaNome)
                    .addComponent(txtNomeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirPeso)
                    .addComponent(btnBuscaPeso)
                    .addComponent(txtPesoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNPesoBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluirAltura)
                            .addComponent(btnBuscaAltura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluirIdade)
                            .addComponent(btnBuscaIdade)
                            .addComponent(txtIdadeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdadeBusca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluirEspec)
                            .addComponent(btnBuscar)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAlturaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAlturaBusca)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        try {
            String nome = txtNome.getText();
            double peso = Double.parseDouble(txtPeso.getText());
            double altura = Double.parseDouble(txtAltura.getText());
            int idade = Integer.parseInt(txtIdade.getText());
            if(nome.equals("")) {
                throw new CampoVazioException();
            } else if(peso < 0) {
                throw new NumeroInvalidoException();
            } else if(altura < 0) {
                throw new NumeroInvalidoException();
            } else if(idade < 0) {
                throw new NumeroInvalidoException();
            }
            atleta.cadAtleta(nome, peso, altura, idade);
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
        } catch (CampoVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo só aceita número");
        } catch (NumeroInvalidoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnCadActionPerformed

    private void txtPesoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoBuscaActionPerformed

    private void btnMediaPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaPesoActionPerformed
        JOptionPane.showMessageDialog(null, "Média dos pesos dos atletas: " + atleta.mediaPeso());
    }//GEN-LAST:event_btnMediaPesoActionPerformed

    private void btnMaisAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisAltoActionPerformed
        JOptionPane.showMessageDialog(null, "Atleta mais alto:\n\n" + atleta.atletaMaisAlto());
    }//GEN-LAST:event_btnMaisAltoActionPerformed

    private void btnMaiorMenorIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaiorMenorIdadeActionPerformed
        JOptionPane.showMessageDialog(null, "Quantidade de Maiores de Idade: " + atleta.qtdMaiorIdade() + "\nQuantidade de Menores de Idade: " + atleta.qtdMenorIdade());
    }//GEN-LAST:event_btnMaiorMenorIdadeActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        JOptionPane.showMessageDialog(null, atleta.listarCadastrados());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBuscaIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaIdadeActionPerformed
        try {
            JOptionPane.showMessageDialog(null, atleta.buscarPorIdade(Integer.parseInt(txtIdadeBusca.getText())));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo só aceita número");
        }
    }//GEN-LAST:event_btnBuscaIdadeActionPerformed

    private void btnBuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaNomeActionPerformed
        try {
            JOptionPane.showMessageDialog(null, atleta.buscarPorNome(txtNomeBusca.getText()));
        } catch (CampoVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscaNomeActionPerformed

    private void btnBuscaPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaPesoActionPerformed
        try {
            JOptionPane.showMessageDialog(null, atleta.buscarPorPeso(Double.parseDouble(txtPesoBusca.getText())));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo só aceita número");
        }
    }//GEN-LAST:event_btnBuscaPesoActionPerformed

    private void btnBuscaAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaAlturaActionPerformed
        try {
            JOptionPane.showMessageDialog(null, atleta.buscarPorAltura(Double.parseDouble(txtAlturaBusca.getText())));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo só aceita número");
        }
    }//GEN-LAST:event_btnBuscaAlturaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            JOptionPane.showMessageDialog(null, atleta.buscarGeral(Integer.parseInt(txtCodigoBusca.getText()) ,txtNomeBusca.getText(), Double.parseDouble(txtPesoBusca.getText()), Double.parseDouble(txtAlturaBusca.getText()), Integer.parseInt(txtIdadeBusca.getText())));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo só aceita número");
        } catch (CampoVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExcluirNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirNomeActionPerformed
        try {
            if(txtNomeBusca.getText().equals("")) {
                throw new CampoVazioException();
            }
            boolean resposta = atleta.excluirPorNome(txtNomeBusca.getText());
            if(resposta == true) {
                JOptionPane.showMessageDialog(null, "Excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi encontrado nenhum atleta.");
            }
        } catch (CampoVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirNomeActionPerformed

    private void btnExcluirPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPesoActionPerformed
        try {
            if(txtPesoBusca.getText().equals("")) {
                throw new CampoVazioException();
            }
            boolean resposta = atleta.excluirPorPeso(Double.parseDouble(txtPesoBusca.getText()));
            if(resposta == true) {
                JOptionPane.showMessageDialog(null, "Excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi encontrado nenhum atleta.");
            }
        } catch (CampoVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirPesoActionPerformed

    private void btnExcluirAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAlturaActionPerformed
        try {
            if(txtAlturaBusca.getText().equals("")) {
                throw new CampoVazioException();
            }
            boolean resposta = atleta.excluirPorAltura(Double.parseDouble(txtAlturaBusca.getText()));
            if(resposta == true) {
                JOptionPane.showMessageDialog(null, "Excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi encontrado nenhum atleta.");
            }
        } catch (CampoVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirAlturaActionPerformed

    private void btnExcluirIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirIdadeActionPerformed
        try {
            if(txtIdadeBusca.getText().equals("")) {
                throw new CampoVazioException();
            }
            boolean resposta = atleta.excluirPorIdade(Integer.parseInt(txtIdadeBusca.getText()));
            if(resposta == true) {
                JOptionPane.showMessageDialog(null, "Excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi encontrado nenhum atleta.");
            }
        } catch (CampoVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirIdadeActionPerformed

    private void btnExcluirEspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEspecActionPerformed
        try {
            if(txtCodigoBusca.getText().equals("") || txtNomeBusca.getText().equals("") || txtPesoBusca.getText().equals("") || txtAlturaBusca.getText().equals("") || txtIdadeBusca.getText().equals("")) {
                throw new CampoVazioException();
            }
            boolean resposta = atleta.excluirPorEspec(Integer.parseInt(txtCodigoBusca.getText()) ,txtNomeBusca.getText(), Double.parseDouble(txtPesoBusca.getText()), Double.parseDouble(txtAlturaBusca.getText()), Integer.parseInt(txtIdadeBusca.getText()));
            if(resposta == true) {
                JOptionPane.showMessageDialog(null, "Excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi encontrado nenhum atleta.");
            }
        } catch (CampoVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo só aceita número");
        }
    }//GEN-LAST:event_btnExcluirEspecActionPerformed

    private void btnBuscaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCodigoActionPerformed
        try {
            JOptionPane.showMessageDialog(null, atleta.buscarPorCodigo(Integer.parseInt(txtCodigoBusca.getText())));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo só aceita número");
        }
    }//GEN-LAST:event_btnBuscaCodigoActionPerformed

    private void btnExcluirCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCodigoActionPerformed
        try {
            if(txtCodigoBusca.getText().equals("")) {
                throw new CampoVazioException();
            }
             boolean resposta = atleta.excluirPorCodigo(Integer.parseInt(txtCodigoBusca.getText()));
            if(resposta == true) {
                JOptionPane.showMessageDialog(null, "Excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi encontrado nenhum atleta.");
            }
        } catch (CampoVazioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo só aceita número");
        }
    }//GEN-LAST:event_btnExcluirCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaAltura;
    private javax.swing.JButton btnBuscaCodigo;
    private javax.swing.JButton btnBuscaIdade;
    private javax.swing.JButton btnBuscaNome;
    private javax.swing.JButton btnBuscaPeso;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnExcluirAltura;
    private javax.swing.JButton btnExcluirCodigo;
    private javax.swing.JButton btnExcluirEspec;
    private javax.swing.JButton btnExcluirIdade;
    private javax.swing.JButton btnExcluirNome;
    private javax.swing.JButton btnExcluirPeso;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMaiorMenorIdade;
    private javax.swing.JButton btnMaisAlto;
    private javax.swing.JButton btnMediaPeso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblAlturaBusca;
    private javax.swing.JLabel lblCodigoBusca;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblIdadeBusca;
    private javax.swing.JLabel lblNPesoBusca;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeBusca;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAlturaBusca;
    private javax.swing.JTextField txtCodigoBusca;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtIdadeBusca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeBusca;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPesoBusca;
    // End of variables declaration//GEN-END:variables
}
